package com.github.sportstats.commons.enumeration;

import java.util.Optional;

/**
 * Represents available choices for country value.
 *
 * @author noavarice
 */
public enum Country implements IIdentifiedEnum {

  AF(1, "AF", "Afghanistan"),
  AL(2, "AL", "Albania"),
  DZ(3, "DZ", "Algeria"),
  AS(4, "AS", "American Samoa"),
  AD(5, "AD", "Andorra"),
  AO(6, "AO", "Angola"),
  AI(7, "AI", "Anguilla"),
  AQ(8, "AQ", "Antarctica"),
  AG(9, "AG", "Antigua and Barbuda"),
  AR(10, "AR", "Argentina"),
  AM(11, "AM", "Armenia"),
  AW(12, "AW", "Aruba"),
  AU(13, "AU", "Australia"),
  AT(14, "AT", "Austria"),
  AZ(15, "AZ", "Azerbaijan"),
  BS(16, "BS", "Bahamas"),
  BH(17, "BH", "Bahrain"),
  BD(18, "BD", "Bangladesh"),
  BB(19, "BB", "Barbados"),
  BY(20, "BY", "Belarus"),
  BE(21, "BE", "Belgium"),
  BZ(22, "BZ", "Belize"),
  BJ(23, "BJ", "Benin"),
  BM(24, "BM", "Bermuda"),
  BT(25, "BT", "Bhutan"),
  BO(26, "BO", "Bolivia"),
  BA(27, "BA", "Bosnia and Herzegovina"),
  BW(28, "BW", "Botswana"),
  BV(29, "BV", "Bouvet Island"),
  BR(30, "BR", "Brazil"),
  IO(31, "IO", "British Indian Ocean Territory"),
  BN(32, "BN", "Brunei Darussalam"),
  BG(33, "BG", "Bulgaria"),
  BF(34, "BF", "Burkina Faso"),
  BI(35, "BI", "Burundi"),
  KH(36, "KH", "Cambodia"),
  CM(37, "CM", "Cameroon"),
  CA(38, "CA", "Canada"),
  CV(39, "CV", "Cape Verde"),
  KY(40, "KY", "Cayman Islands"),
  CF(41, "CF", "Central African Republic"),
  TD(42, "TD", "Chad"),
  CL(43, "CL", "Chile"),
  CN(44, "CN", "China"),
  CX(45, "CX", "Christmas Island"),
  CC(46, "CC", "Cocos (Keeling) Islands"),
  CO(47, "CO", "Colombia"),
  KM(48, "KM", "Comoros"),
  CG(49, "CG", "Congo"),
  CD(50, "CD", "Congo, the Democratic Republic of the"),
  CK(51, "CK", "Cook Islands"),
  CR(52, "CR", "Costa Rica"),
  CI(53, "CI", "Cote D'Ivoire"),
  HR(54, "HR", "Croatia"),
  CU(55, "CU", "Cuba"),
  CY(56, "CY", "Cyprus"),
  CZ(57, "CZ", "Czech Republic"),
  DK(58, "DK", "Denmark"),
  DJ(59, "DJ", "Djibouti"),
  DM(60, "DM", "Dominica"),
  DO(61, "DO", "Dominican Republic"),
  EC(62, "EC", "Ecuador"),
  EG(63, "EG", "Egypt"),
  SV(64, "SV", "El Salvador"),
  GQ(65, "GQ", "Equatorial Guinea"),
  ER(66, "ER", "Eritrea"),
  EE(67, "EE", "Estonia"),
  ET(68, "ET", "Ethiopia"),
  FK(69, "FK", "Falkland Islands (Malvinas)"),
  FO(70, "FO", "Faroe Islands"),
  FJ(71, "FJ", "Fiji"),
  FI(72, "FI", "Finland"),
  FR(73, "FR", "France"),
  GF(74, "GF", "French Guiana"),
  PF(75, "PF", "French Polynesia"),
  TF(76, "TF", "French Southern Territories"),
  GA(77, "GA", "Gabon"),
  GM(78, "GM", "Gambia"),
  GE(79, "GE", "Georgia"),
  DE(80, "DE", "Germany"),
  GH(81, "GH", "Ghana"),
  GI(82, "GI", "Gibraltar"),
  GR(83, "GR", "Greece"),
  GL(84, "GL", "Greenland"),
  GD(85, "GD", "Grenada"),
  GP(86, "GP", "Guadeloupe"),
  GU(87, "GU", "Guam"),
  GT(88, "GT", "Guatemala"),
  GN(89, "GN", "Guinea"),
  GW(90, "GW", "Guinea-Bissau"),
  GY(91, "GY", "Guyana"),
  HT(92, "HT", "Haiti"),
  HM(93, "HM", "Heard Island and Mcdonald Islands"),
  VA(94, "VA", "Holy See (Vatican City State)"),
  HN(95, "HN", "Honduras"),
  HK(96, "HK", "Hong Kong"),
  HU(97, "HU", "Hungary"),
  IS(98, "IS", "Iceland"),
  IN(99, "IN", "India"),
  ID(100, "ID", "Indonesia"),
  IR(101, "IR", "Iran, Islamic Republic of"),
  IQ(102, "IQ", "Iraq"),
  IE(103, "IE", "Ireland"),
  IL(104, "IL", "Israel"),
  IT(105, "IT", "Italy"),
  JM(106, "JM", "Jamaica"),
  JP(107, "JP", "Japan"),
  JO(108, "JO", "Jordan"),
  KZ(109, "KZ", "Kazakhstan"),
  KE(110, "KE", "Kenya"),
  KI(111, "KI", "Kiribati"),
  KP(112, "KP", "Korea, Democratic People's Republic of"),
  KR(113, "KR", "Korea, Republic of"),
  KW(114, "KW", "Kuwait"),
  KG(115, "KG", "Kyrgyzstan"),
  LA(116, "LA", "Lao People's Democratic Republic"),
  LV(117, "LV", "Latvia"),
  LB(118, "LB", "Lebanon"),
  LS(119, "LS", "Lesotho"),
  LR(120, "LR", "Liberia"),
  LY(121, "LY", "Libyan Arab Jamahiriya"),
  LI(122, "LI", "Liechtenstein"),
  LT(123, "LT", "Lithuania"),
  LU(124, "LU", "Luxembourg"),
  MO(125, "MO", "Macao"),
  MK(126, "MK", "Macedonia, the Former Yugoslav Republic of"),
  MG(127, "MG", "Madagascar"),
  MW(128, "MW", "Malawi"),
  MY(129, "MY", "Malaysia"),
  MV(130, "MV", "Maldives"),
  ML(131, "ML", "Mali"),
  MT(132, "MT", "Malta"),
  MH(133, "MH", "Marshall Islands"),
  MQ(134, "MQ", "Martinique"),
  MR(135, "MR", "Mauritania"),
  MU(136, "MU", "Mauritius"),
  YT(137, "YT", "Mayotte"),
  MX(138, "MX", "Mexico"),
  FM(139, "FM", "Micronesia, Federated States of"),
  MD(140, "MD", "Moldova, Republic of"),
  MC(141, "MC", "Monaco"),
  MN(142, "MN", "Mongolia"),
  MS(143, "MS", "Montserrat"),
  MA(144, "MA", "Morocco"),
  MZ(145, "MZ", "Mozambique"),
  MM(146, "MM", "Myanmar"),
  NA(147, "NA", "Namibia"),
  NR(148, "NR", "Nauru"),
  NP(149, "NP", "Nepal"),
  NL(150, "NL", "Netherlands"),
  AN(151, "AN", "Netherlands Antilles"),
  NC(152, "NC", "New Caledonia"),
  NZ(153, "NZ", "New Zealand"),
  NI(154, "NI", "Nicaragua"),
  NE(155, "NE", "Niger"),
  NG(156, "NG", "Nigeria"),
  NU(157, "NU", "Niue"),
  NF(158, "NF", "Norfolk Island"),
  MP(159, "MP", "Northern Mariana Islands"),
  NO(160, "NO", "Norway"),
  OM(161, "OM", "Oman"),
  PK(162, "PK", "Pakistan"),
  PW(163, "PW", "Palau"),
  PS(164, "PS", "Palestinian Territory, Occupied"),
  PA(165, "PA", "Panama"),
  PG(166, "PG", "Papua New Guinea"),
  PY(167, "PY", "Paraguay"),
  PE(168, "PE", "Peru"),
  PH(169, "PH", "Philippines"),
  PN(170, "PN", "Pitcairn"),
  PL(171, "PL", "Poland"),
  PT(172, "PT", "Portugal"),
  PR(173, "PR", "Puerto Rico"),
  QA(174, "QA", "Qatar"),
  RE(175, "RE", "Reunion"),
  RO(176, "RO", "Romania"),
  RU(177, "RU", "Russian Federation"),
  RW(178, "RW", "Rwanda"),
  SH(179, "SH", "Saint Helena"),
  KN(180, "KN", "Saint Kitts and Nevis"),
  LC(181, "LC", "Saint Lucia"),
  PM(182, "PM", "Saint Pierre and Miquelon"),
  VC(183, "VC", "Saint Vincent and the Grenadines"),
  WS(184, "WS", "Samoa"),
  SM(185, "SM", "San Marino"),
  ST(186, "ST", "Sao Tome and Principe"),
  SA(187, "SA", "Saudi Arabia"),
  SN(188, "SN", "Senegal"),
  CS(189, "CS", "Serbia and Montenegro"),
  SC(190, "SC", "Seychelles"),
  SL(191, "SL", "Sierra Leone"),
  SG(192, "SG", "Singapore"),
  SK(193, "SK", "Slovakia"),
  SI(194, "SI", "Slovenia"),
  SB(195, "SB", "Solomon Islands"),
  SO(196, "SO", "Somalia"),
  ZA(197, "ZA", "South Africa"),
  GS(198, "GS", "South Georgia and the South Sandwich Islands"),
  ES(199, "ES", "Spain"),
  LK(200, "LK", "Sri Lanka"),
  SD(201, "SD", "Sudan"),
  SR(202, "SR", "Suriname"),
  SJ(203, "SJ", "Svalbard and Jan Mayen"),
  SZ(204, "SZ", "Swaziland"),
  SE(205, "SE", "Sweden"),
  CH(206, "CH", "Switzerland"),
  SY(207, "SY", "Syrian Arab Republic"),
  TW(208, "TW", "Taiwan, Province of China"),
  TJ(209, "TJ", "Tajikistan"),
  TZ(210, "TZ", "Tanzania, United Republic of"),
  TH(211, "TH", "Thailand"),
  TL(212, "TL", "Timor-Leste"),
  TG(213, "TG", "Togo"),
  TK(214, "TK", "Tokelau"),
  TO(215, "TO", "Tonga"),
  TT(216, "TT", "Trinidad and Tobago"),
  TN(217, "TN", "Tunisia"),
  TR(218, "TR", "Turkey"),
  TM(219, "TM", "Turkmenistan"),
  TC(220, "TC", "Turks and Caicos Islands"),
  TV(221, "TV", "Tuvalu"),
  UG(222, "UG", "Uganda"),
  UA(223, "UA", "Ukraine"),
  AE(224, "AE", "United Arab Emirates"),
  GB(225, "GB", "United Kingdom"),
  US(226, "US", "United States"),
  UM(227, "UM", "United States Minor Outlying Islands"),
  UY(228, "UY", "Uruguay"),
  UZ(229, "UZ", "Uzbekistan"),
  VU(230, "VU", "Vanuatu"),
  VE(231, "VE", "Venezuela"),
  VN(232, "VN", "Viet Nam"),
  VG(233, "VG", "Virgin Islands, British"),
  VI(234, "VI", "Virgin Islands, U.s."),
  WF(235, "WF", "Wallis and Futuna"),
  EH(236, "EH", "Western Sahara"),
  YE(237, "YE", "Yemen"),
  ZM(238, "ZM", "Zambia"),
  ZW(239, "ZW", "Zimbabwe"),
  ;

  private final int id;

  private final String code;

  private final String name;

  Country(int id, String code, String name) {
    this.id = id;
    this.code = code;
    this.name = name;
  }

  @Override
  public int getId() {
    return id;
  }

  public String getCode() {
    return code;
  }

  public String getName() {
    return name;
  }

  public static Optional<Country> of(final Integer id) {
    if (id == null) {
      return Optional.empty();
    }

    for (final Country country: values()) {
      if (id.equals(country.id)) {
        return Optional.of(country);
      }
    }

    return Optional.empty();
  }
}
